/* <![CDATA[ */
var WIKICRIMES_TIPO_CRIME_ROUBO = '4';
var WIKICRIMES_TIPO_CRIME_FURTO = '3';
var WIKICRIMES_TIPO_CRIME_OUTROS = '5';
var WIKICRIMES_TIPO_CRIME_TENTATIVA_ROUBO = '1';
var WIKICRIMES_TIPO_CRIME_TENTATIVA_FURTO = '2';
var WIKICRIMES_SUB_TIPO_CRIME_PESSOA = '1';
var WIKICRIMES_SUB_TIPO_CRIME_PROPRIEDADE = '2';
var WIKICRIMES_SUB_TIPO_CRIME_RIXAS_BRIGAS = '3';
var WIKICRIMES_SUB_TIPO_CRIME_VIOLENCIA_DOMESTICA = '4';
var WIKICRIMES_SUB_TIPO_CRIME_ABUSO_AUTORIDADE = '5';
var WIKICRIMES_SUB_TIPO_CRIME_HOMICIDIO = '6';
var WIKICRIMES_SUB_TIPO_CRIME_TENTATIVA_HOMICIDIO = '7';
var WIKICRIMES_SUB_TIPO_CRIME_LATROCINIO = '8';
/* ]]> */